version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc
  settings:
    govet:
      enable:
        - shadow
    misspell:
      locale: US
    gosec:
      excludes:
        - G117
  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jensholdgaard/discord-dkp-bot
