version: 2

project_name: dkpbot

before:
  hooks:
    - go mod tidy

builds:
  - id: dkpbot
    main: ./cmd/dkpbot
    binary: dkpbot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

dockers_v2:
  - ids:
      - dkpbot
    images:
      - "ghcr.io/jensholdgaard/dkpbot"
    tags:
      - "{{ .Tag }}"
      - latest
    dockerfile: Dockerfile
    sbom: false
    build_flag_templates:
      - "--build-arg=BINARY={{ .Os }}/{{ .Arch }}/dkpbot"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
    platforms:
      - linux/amd64

release:
  prerelease: auto
  mode: replace

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
